[workspace]
resolver = "2"
members = [
    "crates/clip-engine-core",
    "crates/clip-engine",
    "crates/clip-engine-recorder-protocol",
    "crates/clip-engine-recorder",
]

[workspace.package]
version = "1.1.5"
edition = "2021"
rust-version = "1.95"
license = "MIT"
authors = ["DAB"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
